server:
  port: 8761
  shutdown: graceful

spring:
  application:
    name: service-registry
  lifecycle:
    timeout-per-shutdown-phase: 30s

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
